name: Server
version: 1.0.0
main: at.ahit.server.main.Main

commands:
  stats:
    description: /stats {on,off}
  coins:
    description: /coins
  never:
    description: /never
  questinfo:
    description: /questinfo
  mine:
    description: /nein