name: Server
version: 1.0.0
main: at.ahit.server.main.Main
api-version: 1.13

commands:
  stats:
    description: /stats {on,off}
  coins:
    description: /coins
  questinfo:
    description: /questinfo
  aquest:
    description: /aquest
  mine:
    description: /nein
  skillshop:
    description: /skillshop
  setcoins:
    description: /setcoins <Player> <Amount>
  setval:
    description: /setval <Path> <Value>
  getval:
    description: /getval <Path>
  auction:
    description: /auction
  shop:
    description: /shop
  protect:
    description: /protect